name: urbanpy
channels:
    - conda-forge
    - akoda
dependencies:
# required
- fiona>=1.7
- pandas>=0.23.4
- pyproj>=2.2.0
- shapely>=1.5
- sphinx>=2.4.1

# plotting
- descartes>=1.0
- matplotlib>=2.0

# spatial access methods
- rtree>=0.8

# network analysis
- osmnx

# hexagons
- h3

# geospatial
- gdal>=3.0.4
- libgdal>=3.0.4
- proj>=6.3.0
- geos>=3.8.0

#pip dependencies
- pip:
- numpy
- numba
- scikit-learn
- requests
- tqdm
- numpydoc
